// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: atomone/coredaos/v1/tx.proto

package coredaosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_AnnotateProposal_FullMethodName   = "/atomone.coredaos.v1.Msg/AnnotateProposal"
	Msg_EndorseProposal_FullMethodName    = "/atomone.coredaos.v1.Msg/EndorseProposal"
	Msg_ExtendVotingPeriod_FullMethodName = "/atomone.coredaos.v1.Msg/ExtendVotingPeriod"
	Msg_VetoProposal_FullMethodName       = "/atomone.coredaos.v1.Msg/VetoProposal"
	Msg_UpdateParams_FullMethodName       = "/atomone.coredaos.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the Msg service.
type MsgClient interface {
	// AnnotateProposal defines a method to annotate a proposal with additional information.
	// It is only available to the Steering DAO.
	AnnotateProposal(ctx context.Context, in *MsgAnnotateProposal, opts ...grpc.CallOption) (*MsgAnnotateProposalResponse, error)
	// EndorseProposal defines a method to endorse a proposal, and for law proposals this also
	// results in the lowering of the passing threshold to the passing threshold of regular proposals.
	// It is only available to the Steering DAO.
	EndorseProposal(ctx context.Context, in *MsgEndorseProposal, opts ...grpc.CallOption) (*MsgEndorseProposalResponse, error)
	// ExtendVotingPeriod defines a method to extend the voting period of a proposal.
	// It is available to both the Steering DAO and the Oversight DAO.
	ExtendVotingPeriod(ctx context.Context, in *MsgExtendVotingPeriod, opts ...grpc.CallOption) (*MsgExtendVotingPeriodResponse, error)
	// VetoProposal defines a method to veto a proposal.
	// It is only available to the Oversight DAO.
	VetoProposal(ctx context.Context, in *MsgVetoProposal, opts ...grpc.CallOption) (*MsgVetoProposalResponse, error)
	// UpdateParams defines a governance operation for updating the x/coredaos
	// module parameters. The authority is defined in the keeper.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AnnotateProposal(ctx context.Context, in *MsgAnnotateProposal, opts ...grpc.CallOption) (*MsgAnnotateProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAnnotateProposalResponse)
	err := c.cc.Invoke(ctx, Msg_AnnotateProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EndorseProposal(ctx context.Context, in *MsgEndorseProposal, opts ...grpc.CallOption) (*MsgEndorseProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgEndorseProposalResponse)
	err := c.cc.Invoke(ctx, Msg_EndorseProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExtendVotingPeriod(ctx context.Context, in *MsgExtendVotingPeriod, opts ...grpc.CallOption) (*MsgExtendVotingPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgExtendVotingPeriodResponse)
	err := c.cc.Invoke(ctx, Msg_ExtendVotingPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VetoProposal(ctx context.Context, in *MsgVetoProposal, opts ...grpc.CallOption) (*MsgVetoProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgVetoProposalResponse)
	err := c.cc.Invoke(ctx, Msg_VetoProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the Msg service.
type MsgServer interface {
	// AnnotateProposal defines a method to annotate a proposal with additional information.
	// It is only available to the Steering DAO.
	AnnotateProposal(context.Context, *MsgAnnotateProposal) (*MsgAnnotateProposalResponse, error)
	// EndorseProposal defines a method to endorse a proposal, and for law proposals this also
	// results in the lowering of the passing threshold to the passing threshold of regular proposals.
	// It is only available to the Steering DAO.
	EndorseProposal(context.Context, *MsgEndorseProposal) (*MsgEndorseProposalResponse, error)
	// ExtendVotingPeriod defines a method to extend the voting period of a proposal.
	// It is available to both the Steering DAO and the Oversight DAO.
	ExtendVotingPeriod(context.Context, *MsgExtendVotingPeriod) (*MsgExtendVotingPeriodResponse, error)
	// VetoProposal defines a method to veto a proposal.
	// It is only available to the Oversight DAO.
	VetoProposal(context.Context, *MsgVetoProposal) (*MsgVetoProposalResponse, error)
	// UpdateParams defines a governance operation for updating the x/coredaos
	// module parameters. The authority is defined in the keeper.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) AnnotateProposal(context.Context, *MsgAnnotateProposal) (*MsgAnnotateProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnnotateProposal not implemented")
}
func (UnimplementedMsgServer) EndorseProposal(context.Context, *MsgEndorseProposal) (*MsgEndorseProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndorseProposal not implemented")
}
func (UnimplementedMsgServer) ExtendVotingPeriod(context.Context, *MsgExtendVotingPeriod) (*MsgExtendVotingPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendVotingPeriod not implemented")
}
func (UnimplementedMsgServer) VetoProposal(context.Context, *MsgVetoProposal) (*MsgVetoProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VetoProposal not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_AnnotateProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAnnotateProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AnnotateProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AnnotateProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AnnotateProposal(ctx, req.(*MsgAnnotateProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EndorseProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEndorseProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EndorseProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_EndorseProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EndorseProposal(ctx, req.(*MsgEndorseProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExtendVotingPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExtendVotingPeriod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExtendVotingPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ExtendVotingPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExtendVotingPeriod(ctx, req.(*MsgExtendVotingPeriod))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VetoProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVetoProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VetoProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_VetoProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VetoProposal(ctx, req.(*MsgVetoProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atomone.coredaos.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnnotateProposal",
			Handler:    _Msg_AnnotateProposal_Handler,
		},
		{
			MethodName: "EndorseProposal",
			Handler:    _Msg_EndorseProposal_Handler,
		},
		{
			MethodName: "ExtendVotingPeriod",
			Handler:    _Msg_ExtendVotingPeriod_Handler,
		},
		{
			MethodName: "VetoProposal",
			Handler:    _Msg_VetoProposal_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atomone/coredaos/v1/tx.proto",
}
