// Code generated by MockGen. DO NOT EDIT.
// Source: x/dynamicfee/ante/expected_keepers.go

// Package ante_test is a generated GoMock package.
package ante_test

import (
	context "context"
	reflect "reflect"

	types "github.com/atomone-hub/atomone/x/dynamicfee/types"
	types0 "github.com/cosmos/cosmos-sdk/types"
	gomock "github.com/golang/mock/gomock"
)

// MockDynamicfeeKeeper is a mock of DynamicfeeKeeper interface.
type MockDynamicfeeKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicfeeKeeperMockRecorder
}

// MockDynamicfeeKeeperMockRecorder is the mock recorder for MockDynamicfeeKeeper.
type MockDynamicfeeKeeperMockRecorder struct {
	mock *MockDynamicfeeKeeper
}

// NewMockDynamicfeeKeeper creates a new mock instance.
func NewMockDynamicfeeKeeper(ctrl *gomock.Controller) *MockDynamicfeeKeeper {
	mock := &MockDynamicfeeKeeper{ctrl: ctrl}
	mock.recorder = &MockDynamicfeeKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicfeeKeeper) EXPECT() *MockDynamicfeeKeeperMockRecorder {
	return m.recorder
}

// GetMinGasPrice mocks base method.
func (m *MockDynamicfeeKeeper) GetMinGasPrice(arg0 context.Context, arg1 string) (types0.DecCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinGasPrice", arg0, arg1)
	ret0, _ := ret[0].(types0.DecCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinGasPrice indicates an expected call of GetMinGasPrice.
func (mr *MockDynamicfeeKeeperMockRecorder) GetMinGasPrice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinGasPrice", reflect.TypeOf((*MockDynamicfeeKeeper)(nil).GetMinGasPrice), arg0, arg1)
}

// GetParams mocks base method.
func (m *MockDynamicfeeKeeper) GetParams(arg0 context.Context) (types.Params, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParams", arg0)
	ret0, _ := ret[0].(types.Params)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParams indicates an expected call of GetParams.
func (mr *MockDynamicfeeKeeperMockRecorder) GetParams(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParams", reflect.TypeOf((*MockDynamicfeeKeeper)(nil).GetParams), arg0)
}

// MockAccountKeeper is a mock of AccountKeeper interface.
type MockAccountKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockAccountKeeperMockRecorder
}

// MockAccountKeeperMockRecorder is the mock recorder for MockAccountKeeper.
type MockAccountKeeperMockRecorder struct {
	mock *MockAccountKeeper
}

// NewMockAccountKeeper creates a new mock instance.
func NewMockAccountKeeper(ctrl *gomock.Controller) *MockAccountKeeper {
	mock := &MockAccountKeeper{ctrl: ctrl}
	mock.recorder = &MockAccountKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountKeeper) EXPECT() *MockAccountKeeperMockRecorder {
	return m.recorder
}

// GetAccount mocks base method.
func (m *MockAccountKeeper) GetAccount(ctx context.Context, addr types0.AccAddress) types0.AccountI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, addr)
	ret0, _ := ret[0].(types0.AccountI)
	return ret0
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAccountKeeperMockRecorder) GetAccount(ctx, addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAccountKeeper)(nil).GetAccount), ctx, addr)
}

// MockFeeGrantKeeper is a mock of FeeGrantKeeper interface.
type MockFeeGrantKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockFeeGrantKeeperMockRecorder
}

// MockFeeGrantKeeperMockRecorder is the mock recorder for MockFeeGrantKeeper.
type MockFeeGrantKeeperMockRecorder struct {
	mock *MockFeeGrantKeeper
}

// NewMockFeeGrantKeeper creates a new mock instance.
func NewMockFeeGrantKeeper(ctrl *gomock.Controller) *MockFeeGrantKeeper {
	mock := &MockFeeGrantKeeper{ctrl: ctrl}
	mock.recorder = &MockFeeGrantKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeeGrantKeeper) EXPECT() *MockFeeGrantKeeperMockRecorder {
	return m.recorder
}

// UseGrantedFees mocks base method.
func (m *MockFeeGrantKeeper) UseGrantedFees(ctx context.Context, granter, grantee types0.AccAddress, fee types0.Coins, msgs []types0.Msg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseGrantedFees", ctx, granter, grantee, fee, msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UseGrantedFees indicates an expected call of UseGrantedFees.
func (mr *MockFeeGrantKeeperMockRecorder) UseGrantedFees(ctx, granter, grantee, fee, msgs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseGrantedFees", reflect.TypeOf((*MockFeeGrantKeeper)(nil).UseGrantedFees), ctx, granter, grantee, fee, msgs)
}

// MockBankKeeper is a mock of BankKeeper interface.
type MockBankKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockBankKeeperMockRecorder
}

// MockBankKeeperMockRecorder is the mock recorder for MockBankKeeper.
type MockBankKeeperMockRecorder struct {
	mock *MockBankKeeper
}

// NewMockBankKeeper creates a new mock instance.
func NewMockBankKeeper(ctrl *gomock.Controller) *MockBankKeeper {
	mock := &MockBankKeeper{ctrl: ctrl}
	mock.recorder = &MockBankKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankKeeper) EXPECT() *MockBankKeeperMockRecorder {
	return m.recorder
}

// SendCoinsFromAccountToModule mocks base method.
func (m *MockBankKeeper) SendCoinsFromAccountToModule(ctx context.Context, senderAddr types0.AccAddress, recipientModule string, amt types0.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCoinsFromAccountToModule", ctx, senderAddr, recipientModule, amt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCoinsFromAccountToModule indicates an expected call of SendCoinsFromAccountToModule.
func (mr *MockBankKeeperMockRecorder) SendCoinsFromAccountToModule(ctx, senderAddr, recipientModule, amt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCoinsFromAccountToModule", reflect.TypeOf((*MockBankKeeper)(nil).SendCoinsFromAccountToModule), ctx, senderAddr, recipientModule, amt)
}
